### ISSUE TITLE
[Improve] math.sum need to ignore null and undefined value from array

### ISSUE THREAD

**Issue by steve3d** [danrevah/ngx-pipes#166]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

* **Ngx-pipes version:** latest

**Current behavior**
currently, sum will try to sum every element of an array, if this array is plucked from a object which have different properties, then the result of sum will be `NaN` because there are undefined values in array.

**Expected behavior**
sum should ignore undefined values from array, because there is no way to filter out the undefined values from array with pipes.

**Comment by danrevah** [comment]
I don't think that ignoring values is the right approach, it might be misleading, when there's a data corruption the developer should be aware of that.

For your use-case however you could use 'truthify' after 'pluck' in order to get the desired behaviour:
https://github.com/danrevah/ngx-pipes#truthify

You could even probably use 'without: undefined' to make sure only undefined values are being ignoring (I'm not sure about this so you could test it):
https://github.com/danrevah/ngx-pipes#without

**Comment by steve3d** [comment]
truthify seems to be the only solution here
