### ISSUE TITLE
Is there any plan on supporting multiple fields for the 'groupBy' filter?

### ISSUE THREAD

**Issue by shikhartanwar** [danrevah/ngx-pipes#19]
This is not an issue but more of a feature request. The groupBy filter in angular1 supported grouping on multiple fields and generally also it is used for grouping on multiple fields only. Are there any plans in the near future to support that?

**Comment by danrevah** [comment]
Didn't saw such a behaviour in the angular1 filter, but since it's a good idea and it was quite easy to add. I've just released it in version @1.3.0

It now supports multiple fields and nested properties.
Take a look at the documentation: https://github.com/danrevah/ngx-pipes#groupby

Let me know if you have any other ideas on improving the functionality of the pipes. 
I'm always open for additional functionality which will give answers to more use-cases.

Thanks.

**Comment by shikhartanwar** [comment]
Awesome!! Thanks for the prompt reply and release. This is really helpful. The groupBy pipe works like a charm for multiple fields as well now.
