### ISSUE TITLE
Feature filter by date

### ISSUE THREAD

**Issue by silvelo** [danrevah/ngx-pipes#28]
It would be great if we can filter an object array by dates. #27

**Comment by silvelo** [comment]
#27

**Comment by danrevah** [comment]
Hi @silvelo,
overall it looks like a good idea. I got 2 issues with that pull request.

1. You've added moment as a dependency and I don't want `ngx-pipes` lib to have any dependencies.
2. naming it `filterByDate`, doesn't sounds right to me. since `filterBy` is very generic and also supports dates which are Javascript's Date() it might be a bit confusing.
I think that a more proper name would be `dateRange` pipe. which should probably supports Date() objects, and string dates as well.

Let's wait with this pull-request for now to see what the community has to say about it.

**Comment by silvelo** [comment]
Hi @danrevah ,
your changes seem good idea. I will add them to my code.

**Comment by danrevah** [comment]
Hi @silvelo, 

Take a look at the reviews in the code I wrote.
only few minor adjustments before we can merge this.

Thank you for your contribution !

**Comment by silvelo** [comment]
I fixed the changes, and add new feature , strict, to include or exclude input filter.

**Comment by danrevah** [comment]
Looks good. 
I will try to find a time to merge this in the following days.

Thanks!
