### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by fierroandroid** [danrevah/ngx-pipes#31]
Hello, I have a problem related to the installation.
Folders are there, no errors, package.json its also ok.
Imported on module

I've done everything and I get  this on console.log

Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:18 ZoneAwareError

node version 6.9.1

Please help! Thanks !

**Comment by danrevah** [comment]
Can you upload your package.json file to see your dependencies?
Are you using webpack ?

**Comment by fierroandroid** [comment]
I updated node js.. the same problem.

I just installed git clone https://github.com/angular/quickstart  my-proj for quick instalation for test
After that I installed ngx-pipes

Here is the package.json
https://drive.google.com/open?id=0B1upaeE_5x_ZVmZKdUtReGxaV0k

Here is the test project.
https://drive.google.com/open?id=0B1upaeE_5x_ZSFU3ZXBDZ21FMUk

Thank you !!!

**Comment by danrevah** [comment]
It seems like an issue with the System.JS configuration.
they have a few issues regarding XHR Loading error's.

Since the `angular/quickstart` looks a bit outdated (it's not even supporting webpack).
and you're working on a new project I would suggest you to uses angular-cli (https://github.com/angular/angular-cli).

Let me know if this works for you.

**Comment by fierroandroid** [comment]
Thank you ! 
Its working with Angular Cli.

**Comment by danrevah** [comment]
Good news 👍
