### ISSUE TITLE
filterBy-Pipe Question

### ISSUE THREAD

**Issue by Meistercoach83** [danrevah/ngx-pipes#39]
Hi,

following situation: I have members that are just club members, then i have players - that have a clubData.passNumber set. How can I filter the players that have this number set and how can i filter the other ones?

**Comment by danrevah** [comment]
I could help you if can provide a JSON example of your data structure

**Comment by Meistercoach83** [comment]
I have the following setup:

```
user1 : {
   firstName: 'Person 1',
    clubData: {
       passNumber: 123456
   }
},
user2:  {
   firstName: 'Person 2',
    clubData: {
       passNumber: 676
   }
},
user3: {
   firstName: 'Person 3'
},
```

**Comment by Meistercoach83** [comment]
And an other question: I have a memberShip Status with the values 0, 1, 2 and 3. How can I filter all values greater than 1?

**Comment by danrevah** [comment]
First `filterBy` pipe didn't support that kind of behaviour. 
But since it did sound like a good idea it does support it now, you can now search without a term if you only want to make sure that property exists. Update `ngx-pipes` to v1.4.7.

If you don't care about the key values of your object ('user1', 'user2', ...).
You can use the `values` pipe in addition to the `filterBy`. 

For example:

```typescript
 users = {
    user1 : {
      firstName: 'Person 1',
      clubData: {
        passNumber: 123456
      }
    },
    user2:  {
      firstName: 'Person 2',
      clubData: {
        passNumber: 676
      }
    },
    user3: {
      firstName: 'Person 3'
    }
  };
```

```html
<p>Users: {{ users | values | filterBy: ['clubData.passNumber'] | json}}</p>
```
About your second question, unfortunately we do not have a pipe for that.

**Comment by Meistercoach83** [comment]
@danrevah: Another question: Is it possible to filterBy a negotiated value? 
for example: I need all users that don´t have a specific value.

**Comment by danrevah** [comment]
Not possible yet. but it might be a good idea for a new pipe. (`filterByNot`)
