### ISSUE TITLE
ngFor doesn't update data with filterBy

### ISSUE THREAD

**Issue by vinsticSmith** [danrevah/ngx-pipes#42]
**I'm submitting a feature request**
```
[ ] bug report
[x] feature request
```

**Current behavior**
use filterBy with ngFor and push item into the array, view does not update

**Minimal reproduction of the problem with instructions**
expression like this
`*ngFor="let item of items | filterBy:['name']: keyword;"`

**What is the motivation / use case for changing the behavior?**
use push() instead of creating a new array
[ngFor doesn't update data with pipe](http://stackoverflow.com/questions/34456430/ngfor-doesnt-update-data-with-pipe-in-angular2)

**Environment:**

* **Angular version:** 2.4.10

* **Browser:** Chrome 57

* **Language:** TypeScript 2.2.1

* **Node:** `node --version` =   6.9.5

**Comment by danrevah** [comment]
I'm not sure if using `push()` instead would be the right approach.
I need to investigate this a bit more, since it looks like adding `pure: false` to the pipe might just solve this with the right change detection strategy, but it could make that pipe behave less efficient.

Hearing more opinions about this case might be good before we try to implement a fix.

**Comment by danrevah** [comment]
Added `@pure: false` to filterBy pipe

**Comment by jayakrishnapulipati** [comment]
Thanks, @danrevah It resolved my problem. These stateless pipes have eaten my time.

**Comment by utiq** [comment]
@danrevah I have the same issue for GroupBy, how can I solve it? and what would be the right syntax to use` pure: false` in case it works the same way than filterBy

**Comment by danrevah** [comment]
@utiq there's an Impure version of this pipe you just need to use `groupByImpure ` instead of `groupBy`.
