### ISSUE TITLE
ngFor orderBy won't update on array Change

### ISSUE THREAD

**Issue by ldoloscan** [danrevah/ngx-pipes#47]
Hello, 

I have this code:
```
<tr *ngFor="let product of products | orderBy: 'id">
   <td>{{ product.id }}</td>
   <td>{{ product.name }}</td>
   <td>{{ product.odooProductId }}</td>
    <td>{{ product.price }} &euro;</td>
</tr>

```

I also have a button to remove a product.
So, the problem is, that when i remove the object from that products array, nothing changes, even the object that I removed won't dissapear from list.

If i remove orderBy Pipe, the code above updates Ok.

What causes this problem, is there a fix ?

Thanks !!

**Comment by danrevah** [comment]
Thanks for letting me know.

Update to `ngx-pipes` v1.5.8

I've added `@pure: false` to the be in order for it to be detected in each cycle.
If that's not solving it for you, try also to change your change detection strategy by adding to your component decorator: `changeDetection: ChangeDetectionStrategy.OnPush`.

**Comment by ldoloscan** [comment]
Thank you Dan for fast response and fix, that helped me.

I wanted also to thank you for such a great library, it's very helpful !!

Keep on doing such greate thisgs, you're awesome man !!!

**Comment by tiger-seo** [comment]
hello.
@danrevah , fixing this issue by using inpure pipe is not the best practice, because this greatly increase number of computation that angular does, even when there was no changes.  maybe this is Ok for small apps, but this is a problem for big apps, especially when source array is huge and is manipulated by more then one pipe. In my case i do:  filter an array, group by predicate, apply pairs pipe to convert to an array, apply initial pipe to take only first 3. With `pure: false` in orderBy pipe the whole chain will recompute all the time :( I suggest to fix this in other way:  1) somehow to parametrize purity of orderBy and groupBy pipes  2) duplicate pipe, i.e. orderBy and orderByInpure, groupBy and groupByInpure
please, see the section `Pure and impure pipes` in https://angular.io/docs/ts/latest/guide/pipes.html

**Comment by danrevah** [comment]
@tiger-seo Thanks. looks like a better practice would be to extend the pipe for impure pipes. 
I will try to take care of that soon.
a pull-request with such a behaviour would be welcome:

```typescript
@Pipe({
  name: 'flyingHeroesImpure',
  pure: false
})
export class FlyingHeroesImpurePipe extends FlyingHeroesPipe {}
```
